### ISSUE TITLE
Nikoderiko 60 fps

### ISSUE THREAD

**Issue by gabri25ele** [StevensND/switch-port-mods#26]
possibile?
thanks for attention

**Comment by StevensND** [comment]
> possibile? thanks for attention

[Done by Fl4sh](https://github.com/Fl4sh9174/Switch-Ultrawide-Mods/blob/main/Nikoderiko%20the%20Magical%20World%20%5B21.9%20Ultrawide%20v1.0.1%5D.zip)

I've been very busy these days due to work and I couldn't mod until today.
